export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const LOAD_TOPMOVIES_SUCCESS = "LOAD_TOPMOVIES_SUCCESS";
export const LOAD_UPCOMINGMOVIES_SUCCESS = "LOAD_UPCOMINGMOVIES_SUCCESS";
export const LOAD_MOVIEVIDEOS_SUCCESS = "LOAD_MOVIEVIDEOS_SUCCESS";
export const LOAD_MOVIEDETAILS_SUCCESS = "LOAD_MOVIEDETAILS_SUCCESS";
export const LOAD_RELATEDMOVIES_SUCCESS = "LOAD_RELATEDMOVIES_SUCCESS";
export const LOAD_SEARCHMOVIES_SUCCESS = "LOAD_SEARCHMOVIES_SUCCESS";

